version: '3'
services:
  metadata.google.internal:
    image: python:3
    command: python3 -m http.server 80
    expose:
      - "80"
    volumes:
      - ./pnb-proxy.json:/computeMetadata/v1/instance/attributes/pnb-proxy:ro
  gcsproxy:
    build:
      context: .
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /application_default_credentials.json
    ports:
      - "8080:80"
    volumes:
      - $HOME/.config/gcloud/application_default_credentials.json:/application_default_credentials.json:ro
